<?php
return [ 
	'blocks' => [ 
		[ 
			'name' => 'text-image',
			'title' => __( 'Text + image', 'ground' ),
			'description' => __( 'Insert text + image', 'ground' ),
			'keywords' => array( 'text-image' ),
			'icon' => 'text',
		],
		[ 
			'name' => 'carousel',
			'title' => __( 'Carousel', 'ground' ),
			'description' => __( 'Display multiple images in a rich gallery.', 'ground' ),
			'keywords' => array( 'carousel' ),
			'icon' => 'format-gallery',
		],
		[ 
			'name' => 'products',
			'title' => __( 'Products', 'ground' ),
			'description' => __( 'Display Woocommerce products', 'ground' ),
			'keywords' => array( 'products' ),
			'icon' => 'cart',
		],
		[ 
			'name' => 'image-background',
			'title' => __( 'Image background', 'ground' ),
			'description' => __( 'Display image background', 'ground' ),
			'keywords' => array( 'image' ),
			'icon' => 'cart',
		],
		[ 
			'name' => 'banner',
			'title' => __( 'Banner', 'ground' ),
			'description' => __( 'Insert banner', 'ground' ),
			'keywords' => array( 'text' ),
			'icon' => 'welcome-view-site',
		],
		[ 
			'name' => 'text-horizontal-scrolled',
			'title' => __( 'Text horizontal scrolled', 'ground' ),
			'description' => __( 'Insert text horizontal scrolled', 'ground' ),
			'keywords' => array( 'text, scroll' ),
			'icon' => 'welcome-view-site',
		],
		[ 
			'name' => 'photo shooting',
			'title' => __( 'Photo shooting', 'ground' ),
			'description' => __( 'Insert photo shooting', 'ground' ),
			'keywords' => array( 'gallery, photos, photo' ),
			'icon' => 'welcome-view-site',
		],
		[ 
			'name' => 'pinned-photo',
			'title' => __( 'Pinned photo', 'ground' ),
			'description' => __( 'Insert pinned photo 2 columns', 'ground' ),
			'keywords' => array( 'gallery, photos, photo' ),
			'icon' => 'welcome-view-site',
		],
		[ 
			'name' => 'topic',
			'title' => __( 'Topic', 'ground' ),
			'description' => __( 'Insert Topic', 'ground' ),
			'keywords' => array( 'topic' ),
			'icon' => 'welcome-view-site',
		],
		[ 
			'name' => 'topic-image',
			'title' => __( 'Topic + Image', 'ground' ),
			'description' => __( 'Insert Topic + Image', 'ground' ),
			'keywords' => array( 'topic-image' ),
			'icon' => 'welcome-view-site',
		],
		[ 
			'name' => 'news',
			'title' => __( 'News', 'ground' ),
			'description' => __( 'Insert news', 'ground' ),
			'keywords' => array( 'news' ),
			'icon' => 'welcome-view-site',
		],
		[ 
			'name' => 'products-category',
			'title' => __( 'Products Category', 'ground' ),
			'description' => __( 'Display Woocommerce products category', 'ground' ),
			'keywords' => array( 'products, category' ),
			'icon' => 'cart',
		],
		[ 
			'name' => 'select-icons',
			'title' => __( 'Icons select', 'ground' ),
			'description' => __( 'Display select icons', 'ground' ),
			'keywords' => array( 'select-icons' ),
			'icon' => 'cart',
		],
		[ 
			'name' => 'table',
			'title' => __( 'Table responsive', 'ground' ),
			'description' => __( 'Display table responsive', 'ground' ),
			'keywords' => array( 'table' ),
			'icon' => 'cart',
		],
		[ 
			'name' => 'card',
			'title' => __( 'Card', 'ground' ),
			'description' => __( 'Display card', 'ground' ),
			'keywords' => array( 'card' ),
			'icon' => 'cart',
		],
		[ 
			'name' => 'accordion',
			'title' => __( 'Accordion', 'ground' ),
			'description' => __( 'Display Accordion', 'ground' ),
			'keywords' => array( 'card' ),
			'icon' => 'editor-ul',
		],
		[ 
			'name' => 'gallery-thumb',
			'title' => __( 'Gallery with thumbnails', 'ground' ),
			'description' => __( 'Display gallery with thumbnails', 'ground' ),
			'keywords' => array( 'card' ),
			'icon' => 'editor-ul',
		],
		[ 
			'name' => 'video-modal',
			'title' => __( 'Video modal', 'ground' ),
			'description' => __( 'Video with modal', 'ground' ),
			'keywords' => array( 'video', 'modal', 'popup' ),
			'icon' => 'video-alt3',
		],
	],
];