<?php
return [
	'post_types' => [
		[
			'name' => 'ground_catalog',
			'args' => [
				'rewrite' => [
					'slug' => sanitize_title( __( 'catalog', 'ground' ) ),
					'with_front' => true,
				],
				'supports' => [
					'title',
					'editor',
					'excerpt',
					'thumbnail',
					'comments',
					'revisions',
					'page-attributes',
				],
				'labels' => [
					'name' => _x( 'Catalog', 'Post Type General Name', 'ground' ),
					'singular_name' => _x( 'Item', 'Post Type Singular Name', 'ground' ),
					'menu_name' => _x( 'Catalog', 'Post Type General Name', 'ground' ),
					'name_admin_bar' => _x( 'Item', 'Post Type Singular Name', 'ground' ),
					'add_new_item' => __( 'Add New Item', 'ground' ),
					'edit_item' => __( 'Edit Item', 'ground' ),
					'new_item' => __( 'New Item', 'ground' ),
					'view_item' => __( 'View Item', 'ground' ),
					'view_items' => __( 'View Items', 'ground' ),
					'search_items' => __( 'Search Items', 'ground' ),
					'not_found' => __( 'No items found.', 'ground' ),
					'not_found_in_trash' => __( 'No items found in Trash.', 'ground' ),
					'all_items' => __( 'All Items', 'ground' ),
					'archives' => __( 'Item Archives', 'ground' ),
					'attributes' => __( 'Item Attributes', 'ground' ),
					'insert_into_item' => __( 'Insert into item', 'ground' ),
					'uploaded_to_this_item' => __( 'Uploaded to this item', 'ground' ),
					'featured_image' => __( 'Featured Image', 'ground' ),
					'set_featured_image' => __( 'Set featured image', 'ground' ),
					'remove_featured_image' => __( 'Remove featured image', 'ground' ),
					'use_featured_image' => __( 'Use as featured image', 'ground' ),
					'filter_items_list' => __( 'Filter items list', 'ground' ),
					'items_list_navigation' => __( 'Items list navigation', 'ground' ),
					'items_list' => __( 'Items list', 'ground' ),
					'item_published' => __( 'Item published.', 'ground' ),
					'item_updated' => __( 'Item updated.', 'ground' ),
					'item_link' => __( 'Item Link', 'ground' ),
					'item_link_description' => __( 'A link to an item.', 'ground' ),
				],
				'has_archive' => false,
				'public' => true,
				'show_in_rest' => true,
				'menu_position' => 5,
				'menu_icon' => 'dashicons-welcome-widgets-menus',
				'exclude_from_search' => false,
			]
		],
	],
	'taxonomies' => [
		[
			'name' => 'ground_catalog_taxonomy',
			'object_type' => 'ground_catalog',
			'args' => [
				'hierarchical' => true,
				'public' => true,
				'show_admin_column' => true,
				'labels' => [
					'name' => _x( 'Categories', 'Taxonomy General Name', 'ground' ),
					'singular_name' => _x( 'Category', 'Taxonomy Singular Name', 'ground' ),
					'menu_name' => _x( 'Categories', 'Taxonomy General Name', 'ground' ),
					'all_items' => __( 'All Categories', 'ground' ),
					'parent_item' => __( 'Parent Category', 'ground' ),
					'parent_item_colon' => __( 'Parent Category:', 'ground' ),
					'new_item_name' => __( 'New Category Name', 'ground' ),
					'add_new_item' => __( 'Add New Category', 'ground' ),
					'edit_item' => __( 'Edit Category', 'ground' ),
					'update_item' => __( 'Update Category', 'ground' ),
					'view_item' => __( 'View Category', 'ground' ),
					'search_items' => __( 'Search Categories', 'ground' ),
					'not_found' => __( 'Not Found', 'ground' ),
					'no_terms' => __( 'No categories', 'ground' ),
					'filter_by_item' => __( 'Filter by category', 'ground' ),
					'items_list_navigation' => __( 'Categories list navigation', 'ground' ),
					'items_list' => __( 'Categories list', 'ground' ),
					'back_to_items' => __( '← Back to Categories', 'ground' ),
				],
				'rewrite' => [
					'slug' => sanitize_title( __( 'catalog-category', 'ground' ) ),
					'hierarchical' => true,
					'with_front' => true,
				],
			]
		],
	],
];
